name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Release"
        uses: "./"
        with:
          command-name: "laminas:automatic-releases:release"
          env:
            "GITHUB_TOKEN": ${{ secrets.ORGANIZATION_ADMIN_TOKEN }}